<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Game_Path>Y:\Games\steamapps\common\Nuclear Option\NuclearOption_Data\Managed</Game_Path>
    <TargetFramework>net48</TargetFramework>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
    <AssemblyName>SLine</AssemblyName>
    <RootNamespace>SLine</RootNamespace>
    <Version>1.7.0</Version>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.3" PrivateAssets="all" ExcludeAssets="runtime"/>
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all"/>
    <PackageReference Include="BepInEx.Core" Version="5.*"/>
  </ItemGroup>
  
  <ItemGroup>
    <Reference Include="mscorlib">
      <HintPath>$(Game_Path)\mscorlib.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="System">
      <HintPath>$(Game_Path)\System.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>$(Game_Path)\System.Core.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="netstandard">
      <HintPath>$(Game_Path)\netstandard.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(Game_Path)\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
      <Publicize>True</Publicize>
    </Reference>
    <Reference Include="Mirage">
      <HintPath>$(Game_Path)\Mirage.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(Game_Path)\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(Game_Path)\UnityEngine.UI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(Game_Path)\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(Game_Path)\UnityEngine.UIModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(Game_Path)\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Rewired_Core">
      <HintPath>$(Game_Path)\Rewired_Core.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="InputFramework">
      <HintPath>$(SolutionDir)\InputFramework.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

</Project>
